services:
  backend:
    build: .
    container_name: frota_main_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks: 
      - frota-net
    environment:
      - DATABASE_URL=postgresql+psycopg2://frota_next_user:frota_next_pass@db:5432/frota_next_db
      - SECRET_KEY=da59f57b85fc59b3c2aa2696f43e88c3c52b4e418a7c7274ba31be40cb117d85

  db:
    image: postgres:15-alpine
    container_name: frota_db_ci
    networks:
      - frota-net
    environment:
      - POSTGRES_USER=frota_next_user
      - POSTGRES_PASSWORD=frota_next_pass
      - POSTGRES_DB=frota_next_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U frota_next_user -d frota_next_db"]
      interval: 5s
      timeout: 5s
      retries: 5

networks: 
  frota-net:
    driver: bridge